--liquibase formatted sql

--changeset kozionov:2023-11-02-001-tables
create table users (id bigint generated by default as identity, email varchar(255), login varchar(255) not null, mobile_number varchar(255), name varchar(255), password varchar(255) not null, surname varchar(255), role_id bigint, primary key (id));

create table role (id bigint generated by default as identity, role_name varchar(255), primary key (id));

create table scores (id bigint generated by default as identity, name varchar(255), val integer, primary key (id));